### ISSUE TITLE
[Bug] 'Fire charge converts to netherrack' doesn't work.

### ISSUE THREAD

**Issue by Megaminx12** [gnembon/carpet-extra#118]
I place a dispenser pointing into a cobblestone block, fill the dispenser with fire charges and power it. The fire charge is used up and there is an animation of the fire charge entering the block, but the block stays cobblestone.

**Comment by Notme2222** [comment]
I am also experiencing this problem

**Comment by altrisi** [comment]
According to #125, this issue was fixed in 263f4a9f2caf1ecdbe3a39d39426397cd7a57c83 and can now be closed.

**Comment by Megaminx12** [comment]
Not fixed. Used latest carpet mod and carpet extra.



[2020-10-11_19-15-02.zip](https://github.com/gnembon/carpet-extra/files/5361662/2020-10-11_19-15-02.zip)

**Comment by Megaminx12** [comment]
@replaceitem Still not fixed.

**Comment by replaceitem** [comment]
Yes the newest release 1.4.11 still doesnt include the fix, @gnembon should release a new build for 1.4.12 so its in sync with carpet mod again and includes the updated stuff

**Comment by DeadlyMC** [comment]
Yup, should be fixed in next release

**Comment by Megaminx12** [comment]
I'll close when it is fixed and I've tested to make sure it works (I'm on the scicraft discord so I know when releases come).

**Comment by Megaminx12** [comment]
I'll close when it is fixed and I've tested to make sure it works (I'm on the scicraft discord so I know when releases come).

**Comment by Megaminx12** [comment]
I'm gonna test now, and if it works I'll close this.

**Comment by Megaminx12** [comment]
Works, thanks for fixing.
